language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_0384c7df4890_key -iv $encrypted_0384c7df4890_iv
  -in deploy_key.enc -out deploy_key -d
- npm install -g gulp
- gem install fpm
script:
- gulp ci
